name: bottom_navigation_spotlight
description: A customizable bottom navigation bar with spotlight effects.
version: 0.1.0
repository: https://github.com/kinleyrabgay/bottom_navigation_spotlight

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0